version: '3.3'
services:
  db:
    image: postgres:13
    restart: unless-stopped
    env_file: .env
    user: '${POSTGRES_USER}'
    ports:
      - '${POSTGRES_LOCAL_PORT}:${POSTGRES_DOCKER_PORT}'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      timeout: 20s
      retries: 10
    volumes:
      - ./dockerize/init.sql:/docker-entrypoint-initdb.d/init.sql